apiVersion: batch/v1
kind: Job
metadata:
  name: mbw
  namespace: default
  labels:
    type: batch-job
    app: pts
spec:
  parallelism: 20
  completions: 2
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: pts
    spec:
      restartPolicy: Never
      containers:
        - name: mbw
          image: lixinqiany/job:mbw_1.5
          resources:
            requests:
              cpu: "1"
              memory: "2400Mi"
            limits:
              cpu: "1"
              memory: "2400Mi"
