apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    type: long-running
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        type: long-running
    spec:
      containers:
      - name: nginx
        image: lixinqiany/long-running:nginx_win_2.2
        ports:
          - containerPort: 80
            name: http
          - containerPort: 9913
            name: metrics
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "128Mi"
---
# 保留原有的 NodePort Service（端口 80）
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-status
  namespace: default
  labels:
    app: nginx
    component: status
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: metrics            # ← ServicePort 的 name，用于 ServiceMonitor.endpoints.port
      protocol: TCP
      port: 80                 # ← 暴露 Pod 上的 80
      targetPort: http
