apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-status-monitor
  namespace: monitoring
  labels:
    app: nginx
    release: prometheus
spec:
  selector:
    matchLabels:
      app: nginx
      component: status        # ← 与 nginx-svc-status 的 labels 一致
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics            # ← 对应 nginx-svc-status.spec.ports[].name
      path: /status/format/prometheus
      scheme: http
      interval: 15s
      scrapeTimeout: 5s
