apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
    type: long-running
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        type: long-running
    spec:
      containers:
      - name: nginx
        image: lixinqiany/long-running:nginx_win_1.17
        ports:
          - containerPort: 80
            name: http
          - containerPort: 9913
            name: metrics
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "150m"
            memory: "256Mi"
---
# 保留原有的 NodePort Service（端口 80）
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
      nodePort: 30080
---
# 新增一个用于暴露 metrics (9913) 的 ClusterIP Service
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-metrics
  namespace: default
  labels:
    app: nginx
    component: exporter
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: metrics
      protocol: TCP
      port: 9913
      targetPort: metrics