apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    type: long-running
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        type: long-running
    spec:
      containers:
      - name: nginx
        image: lixinqiany/long-running:nginx_win_1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"    # 初始值=1/4核CPU
            memory: "256Mi" # 初始值=256MB内存
          limits:
            cpu: "250m"    # 与requests相同
            memory: "256Mi" # 与requests相同
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080