apiVersion: batch/v1
kind: Job
metadata:
  name: renaissance
  namespace: default
  labels:
    type: batch-job
    app: pts
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: pts
    spec:
      containers:
        - name: renaissance
          image: lixinqiany/job:renaissance_1.0
          resources:
            requests:
              cpu: "5"
              memory: "512Mi"
            limits:
              cpu: "5"
              memory: "512Mi"
      restartPolicy: Never
