apiVersion: batch/v1
kind: Job
metadata:
  name: renaissance
  namespace: default
  labels:
    type: batch-job
    app: pts
spec:
  parallelism: 3
  completions: 12
  backoffLimit: 6
  template:
    metadata:
      labels:
        app: pts
    spec:
      containers:
        - name: renaissance
          image: lixinqiany/job:renaissance_1.1
          resources:
            requests:
              cpu: "4"
              memory: "512Mi"
            limits:
              cpu: "4"
              memory: "512Mi"
      restartPolicy: Never
